// Holds values for actions


export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const FETCH_DB_POSTS_SUCCESS = 'FETCH_DB_POSTS_SUCCESS'

export const REMOVE_DB_POSTS = 'REMOVE_DB_POSTS'

export const FETCH_DB_POST_COMMENTS_SUCCESS = 'FETCH_DB_POST_COMMENTS_SUCCESS'

export const DB_POST_COMMENTS_FAILURE = 'DB_POST_COMMENTS_FAILURE'

export const GET_ALL_USERS = 'GET_ALL_USERS'

export const REMOVE_ALL_USERS = 'REMOVE_ALL_USERS'

export const APPOINTMENTS_SUCCESS = 'APPOINTMENTS_SUCCESS'

export const SEARCH_POSTS_SUCCESS = "SEARCH_POSTS_SUCCESS"

export const SEARCH_POSTS_FAILURE = "SEARCH_POSTS_FAILURE"
